---
- hosts: geerydev
  become: yes
    
  tasks:
    - name: Export DB
      shell: docker exec gd-mongodb bash -c "mongodump --uri=mongodb://gd-mongodb:27017 --out=/tmp/home/{{ansible_date_time.iso8601}}"
    - name: Pull down local copy
      synchronize:
        mode: pull
        src: /home/{{ansible_date_time.iso8601}}
        dest: ./data/{{ansible_date_time.iso8601}}
