---
- hosts: geerydev
  become: yes

  tasks:

    - name: update
      shell: apt-get update
      sudo: true
    - name: package install
      shell: apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      sudo: true
    - name: download docker
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: install docker engine
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo: true
    - name: install docker cli
      shell: apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
      sudo: true
    - name: Install letsencrypt
      shell: snap install --classic certbot
      sudo: true
    - name: Install Pip
      shell: apt install -y python-pip
    - name: Install docker-py
      shell: yes | pip install docker-py
